package br.com.softhouse.dende.model;

public enum TipoEvento {
    SOCIAL, CORPORATIVO, ACADEMICO, CULTURAL_ENTRETENIMENTO,
    RELIGIOSO, ESPORTIVO, FEIRA, CONGRESSO, OFICINA, CURSO,
    TREINAMENTO, AULA, SEMINARIO, PALESTRA, SHOW, FESTIVAL,
    EXPOSICAO, RETIRO, CULTO, CELEBRACAO, CAMPEONATO, CORRIDA
}